version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: voucher-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voucher-management-system
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voucher_network

volumes:
  postgres_data:

networks:
  voucher_network:
    driver: bridge
